In [1]:
import numpy as np

# Chapter 01a — NumPy Arrays: the Basics

In Chapter 00 we built lists of numbers with loops and found it clumsy. **NumPy**
fixes this. Its central object is the **array** (`ndarray`): a grid of numbers
that behaves like a vector or a matrix.

The big idea: an array lets you write math on *whole collections of numbers at
once*, in notation that mirrors the page. A vector $\mathbf{v}\in\mathbb{R}^n$
is a 1D array; a matrix $A\in\mathbb{R}^{m\times n}$ is a 2D array.

Run each cell with **Shift + Enter**. You cannot break anything.

___
### 2. Making an array from a list

The simplest way to build an array is `np.array(...)` from a Python list.
Think of this as writing down a vector $\mathbf{v} = (2, 3, 5, 7)$.

In [2]:
v = np.array([2, 3, 5, 7])   # a 1D array = a vector
print(v)
print(type(v))               # <class 'numpy.ndarray'>

[2 3 5 7]
<class 'numpy.ndarray'>


A list of lists becomes a 2D array — a **matrix**. Each inner list is a row.

$$A = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{pmatrix}$$

In [3]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])    # two rows, three columns
print(A)

[[1 2 3]
 [4 5 6]]


____
### 3. Building arrays without typing every number

Typing numbers by hand does not scale. NumPy has factory functions:

| Function | What it makes |
|----------|---------------|
| `np.arange(start, stop, step)` | evenly spaced values, like `range` (stop excluded) |
| `np.linspace(start, stop, num)` | `num` points evenly spaced, **stop included** |
| `np.zeros(shape)` | all zeros |
| `np.ones(shape)` | all ones |
| `np.full(shape, value)` | all equal to `value` |
| `np.eye(n)` | the $n\times n$ identity matrix $I$ |

In [4]:
print(np.arange(0, 10, 2))  # Start at 0, go up by 2, stop before 10.
print(np.linspace(0, 1, 5)) # Give me 5 evenly spaced points from 0 to 1, including 1.

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


**`arange` vs `linspace`.** Use `arange` when you care about the *step size*; use
`linspace` when you care about the *number of points* (and want the endpoint
included). For plotting a smooth function, `linspace` is almost always what you
want.

In [5]:
print(np.linspace(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]


____
### 4. The anatomy of an array: shape, ndim, dtype

Every array carries three useful descriptions:

- `.shape` — a tuple of sizes along each direction, e.g. `(2, 3)` = 2 rows, 3 cols
- `.ndim`  — the number of dimensions (1 for a vector, 2 for a matrix)
- `.dtype` — the type of the numbers (e.g. `int64`, `float64`)

In [8]:
A = np.array([[1, 2, 3],    # Recall, a mx is a list of lists
              [4, 5, 6]])
print("shape :", A.shape)   # (2, 3)
print("ndim  :", A.ndim)    # 2
print("dtype :", A.dtype)   # int64 (the numbers are whole)
print("size  :", A.size)    # 6  total number of elements

shape : (2, 3)
ndim  : 2
dtype : int64
size  : 6


In [11]:
# A single decimal makes the WHOLE array floating-point:
w = np.array([1, 2, 3.0])
print(w)            # [1. 2. 3.]
print(w.dtype)      # float64

# You can also ask for a dtype explicitly:
z = np.array([1, 2, 3], dtype=float)
print(z, z.dtype)

[1. 2. 3.]
float64
[1. 2. 3.] float64


___
### 5. Indexing: reading one element

Indexing starts at **0** (just like Python lists). For a 2D array use
`A[row, col]`.

In [15]:
v = np.array([10, 20, 30, 40, 50])
print(v[0])     # first element -> 10
print(v[-1])    # last element  -> 50

A = np.array([[1, 2, 3],
              [4, 5, 6]])
print(A[0, 0])  # row 0, col 0 -> 1
print(A[1, 2])  # row 1, col 2 -> 6

10
50
1
6


___
### 6. Slicing: reading many elements at once

Slicing uses `start:stop` (stop excluded), exactly like lists. For 2D arrays you
slice each direction, separated by a comma. A lone `:` means "everything in this
direction".

In [18]:
v = np.array([10, 20, 30, 40, 50])
print(v[1:4])    # elements 1,2,3 -> [20 30 40]
print(v[:3])     # first three    -> [10 20 30]
print(v[::2])    # every 2nd one  -> [10 30 50]

print(v[1::2])

[20 30 40]
[10 20 30]
[10 30 50]
[20 40]


In [22]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(A[0, :])     # whole first ROW    -> [1 2 3]
print(A[:, 1])     # whole second COL   -> [2 5 8]
print(A[0:2, 1:3]) # top-right 2x2 block

[1 2 3]
[2 5 8]
[[2 3]
 [5 6]]


___
### 7. Reshaping: same numbers, new layout

`reshape` rearranges the same data into a different shape. The number of
elements must match. A handy trick: pass `-1` for "figure this dimension out for
me".

In [28]:
v = np.arange(12)          # 0,1,...,11  -> shape (12,)
print(v)

M = v.reshape(3, 4)        # 3 rows, 4 cols
print(M)

print(v.reshape(2, -1))    # 2 rows, NumPy infers 6 cols

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


___
### 8. Stacking arrays together

You can glue arrays edge-to-edge. `np.vstack` stacks vertically (adds rows);
`np.hstack` stacks horizontally (adds columns).

In [32]:
r1 = np.array([1, 2, 3])
r2 = np.array([4, 5, 6])

print(np.vstack([r1, r2]))   # stack as two rows -> 2x3 matrix
print(np.hstack([r1, r2]))   # join end to end   -> length-6 vector

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
