In [2]:
import numpy as np

# Chapter 01a — NumPy Arrays: the Basics

In Chapter 00 we built lists of numbers with loops and found it clumsy. **NumPy**
fixes this. Its central object is the **array** (`ndarray`): a grid of numbers
that behaves like a vector or a matrix.

The big idea: an array lets you write math on *whole collections of numbers at
once*, in notation that mirrors the page. A vector $\mathbf{v}\in\mathbb{R}^n$
is a 1D array; a matrix $A\in\mathbb{R}^{m\times n}$ is a 2D array.

Run each cell with **Shift + Enter**. You cannot break anything.

___
### 2. Making an array from a list

The simplest way to build an array is `np.array(...)` from a Python list.
Think of this as writing down a vector $\mathbf{v} = (2, 3, 5, 7)$.

In [3]:
v = np.array([2, 3, 5, 7])   # a 1D array = a vector
print(v)
print(type(v))               # <class 'numpy.ndarray'>

[2 3 5 7]
<class 'numpy.ndarray'>


A list of lists becomes a 2D array — a **matrix**. Each inner list is a row.

$$A = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{pmatrix}$$

In [4]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])    # two rows, three columns
print(A)

[[1 2 3]
 [4 5 6]]


____
### 3. Building arrays without typing every number

Typing numbers by hand does not scale. NumPy has factory functions:

| Function | What it makes |
|----------|---------------|
| `np.arange(start, stop, step)` | evenly spaced values, like `range` (stop excluded) |
| `np.linspace(start, stop, num)` | `num` points evenly spaced, **stop included** |
| `np.zeros(shape)` | all zeros |
| `np.ones(shape)` | all ones |
| `np.full(shape, value)` | all equal to `value` |
| `np.eye(n)` | the $n\times n$ identity matrix $I$ |

In [5]:
print(np.arange(0, 10, 2))  # Start at 0, go up by 2, stop before 10.
print(np.linspace(0, 1, 5)) # Give me 5 evenly spaced points from 0 to 1, including 1.

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


**`arange` vs `linspace`.** Use `arange` when you care about the *step size*; use
`linspace` when you care about the *number of points* (and want the endpoint
included). For plotting a smooth function, `linspace` is almost always what you
want.

In [6]:
print(np.linspace(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]


____
### 4. The anatomy of an array: shape, ndim, dtype

Every array carries three useful descriptions:

- `.shape` — a tuple of sizes along each direction, e.g. `(2, 3)` = 2 rows, 3 cols
- `.ndim`  — the number of dimensions (1 for a vector, 2 for a matrix)
- `.dtype` — the type of the numbers (e.g. `int64`, `float64`)

In [7]:
A = np.array([[1, 2, 3],    # Recall, a mx is a list of lists
              [4, 5, 6]])
print("shape :", A.shape)   # (2, 3)
print("ndim  :", A.ndim)    # 2
print("dtype :", A.dtype)   # int64 (the numbers are whole)
print("size  :", A.size)    # 6  total number of elements

shape : (2, 3)
ndim  : 2
dtype : int64
size  : 6


In [8]:
# A single decimal makes the WHOLE array floating-point:
w = np.array([1, 2, 3.0])
print(w)            # [1. 2. 3.]
print(w.dtype)      # float64

# You can also ask for a dtype explicitly:
z = np.array([1, 2, 3], dtype=float)
print(z, z.dtype)

[1. 2. 3.]
float64
[1. 2. 3.] float64


___
### 5. Indexing: reading one element

Indexing starts at **0** (just like Python lists). For a 2D array use
`A[row, col]`.

In [9]:
v = np.array([10, 20, 30, 40, 50])
print(v[0])     # first element -> 10
print(v[-1])    # last element  -> 50

A = np.array([[1, 2, 3],
              [4, 5, 6]])
print(A[0, 0])  # row 0, col 0 -> 1
print(A[1, 2])  # row 1, col 2 -> 6

10
50
1
6


___
### 6. Slicing: reading many elements at once

Slicing uses `start:stop` (stop excluded), exactly like lists. For 2D arrays you
slice each direction, separated by a comma. A lone `:` means "everything in this
direction".

In [10]:
v = np.array([10, 20, 30, 40, 50])
print(v[1:4])    # elements 1,2,3 -> [20 30 40]
print(v[:3])     # first three    -> [10 20 30]
print(v[::2])    # every 2nd one  -> [10 30 50]

print(v[1::2])

[20 30 40]
[10 20 30]
[10 30 50]
[20 40]


In [11]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(A[0, :])     # whole first ROW    -> [1 2 3]
print(A[:, 1])     # whole second COL   -> [2 5 8]
print(A[0:2, 1:3]) # top-right 2x2 block

[1 2 3]
[2 5 8]
[[2 3]
 [5 6]]


___
### 7. Reshaping: same numbers, new layout

`reshape` rearranges the same data into a different shape. The number of
elements must match. A handy trick: pass `-1` for "figure this dimension out for
me".

In [12]:
v = np.arange(12)          # 0,1,...,11  -> shape (12,)
print(v)

M = v.reshape(3, 4)        # 3 rows, 4 cols
print(M)

print(v.reshape(2, -1))    # 2 rows, NumPy infers 6 cols

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


___
### 8. Stacking arrays together

You can glue arrays edge-to-edge. `np.vstack` stacks vertically (adds rows);
`np.hstack` stacks horizontally (adds columns).

In [13]:
r1 = np.array([1, 2, 3])
r2 = np.array([4, 5, 6])

print(np.vstack([r1, r2]))   # stack as two rows -> 2x3 matrix
print(np.hstack([r1, r2]))   # join end to end   -> length-6 vector

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


___
### 9. Boolean masks: selecting by a condition

Comparing an array with a number gives a **boolean array** (True/False for each
entry). Indexing with that mask keeps only the `True` entries — this is how you
*filter* data. `np.where` picks between two values per entry, and
`np.any`/`np.all` summarize a whole array.

In [14]:
import numpy as np

v = np.array([-2, 5, -1, 3, 0, 8])

mask = v > 0                 # a boolean array
print(mask)                  # [False  True False  True False  True]
print(v[mask])               # [5 3 8]  -> only the positive entries
print(v[v > 0])              # the same, in one step

print("how many > 0 :", np.sum(v > 0))   # True counts as 1 -> 3
print("how many < 0 :", np.sum(v < 0))   # True counts as 1 -> 3
print("any negative?:", np.any(v < 0))   # True
print("all >= 0?    :", np.all(v >= 0))  # False

[False  True False  True False  True]
[5 3 8]
[5 3 8]
how many > 0 : 3
how many < 0 : 2
any negative?: True
all >= 0?    : False


In [15]:
v = np.array([-2, 5, -1, 3, 0, 8])

# np.where(condition, value_if_true, value_if_false).
# Replacing negatives with 0 is exactly the ReLU used in neural networks!
print(np.where(v > 0, v, 0))   # [0 5 0 3 0 8]

# You can also ASSIGN through a mask:
w = v.copy()
w[w < 0] = 0                   # set every negative entry to 0
print(w)                       # [0 5 0 3 0 8]

[0 5 0 3 0 8]
[0 5 0 3 0 8]


___
### 10. Views vs. copies (an important gotcha)

A slice of an array is a **view**: it shares memory with the original, so editing
the slice edits the original too. When you need an independent array, use
`.copy()`.

In [18]:
a = np.array([10, 20, 30, 40])
s = a[1:3]          # a VIEW into a (not a fresh array)
s[0] = 999          # change the view ...
print("a changed!:", a)     # [ 10 999  30  40]  -> the original changed

b = a[1:3].copy()   # an independent COPY
b[0] = -1
print("a is safe :", a)     # original untouched

a changed!: [ 10 999  30  40]
a is safe : [ 10 999  30  40]


____
### ✍️ Exercise 1 (solution included)

Build the $3\times 3$ matrix

$$B = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{pmatrix}$$

using `np.arange` and `reshape` (do **not** type the nine numbers by hand). Then
print its shape, its middle column, and its last row.

In [29]:
A = np.arange(1, 10)
B = A.reshape(3, 3)

print(B)
print(B.shape)
print(B[:, 1])
print(B[2, :])

print(type(B))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[2 5 8]
[7 8 9]
<class 'numpy.ndarray'>


___
### ✍️ Exercise 2 (solution included)

Create 11 evenly spaced points on the interval $[0, 1]$ (including both
endpoints). 

Then pull out (a) the first 5 points and (b) every other point.
*Hint:* this is a job for `linspace`, not `arange`.

In [34]:
A = np.linspace(0, 1, 11)   # 11 evenly spaced pts on the interval [0,1] (incl. both endpts).

B = A[:5]   # the 1st (5) points.
C = A[::2]  # take one point, skip the next, take the next,

print(A)
print(B)
print(C)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[0.  0.1 0.2 0.3 0.4]
[0.  0.2 0.4 0.6 0.8 1. ]


___
### 📝 Homework (no solutions provided)

1. Make a length-10 array of all `5`s in two different ways (one using
   `np.full`, one using `np.ones`).

In [37]:
print(np.full(10, 5))
print(np.ones(10)*5)

[5 5 5 5 5 5 5 5 5 5]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


____
2. Build a $4\times 4$ matrix containing the numbers $0,1,\dots,15$ in
   row-by-row order, then extract its $2\times 2$ bottom-right corner.

In [43]:
A = np.arange(16)

B = A.reshape(4, 4)

print(B)
print(B[2:, 2:])    # 2 x 2 bottom-right corner.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[10 11]
 [14 15]]


___
3. Create the vector $(0, 0.25, 0.5, 0.75, 1.0)$ twice: once with `arange` and
   once with `linspace`. Confirm both give the same numbers.

In [51]:
print(np.arange(0, 1.25, 0.25)) # arange will use any no. pts to get the job done.
print(np.linspace(0, 1, 5)) # linspace uses specified no. of pts to do the job.

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]


____
4. Take `A = np.arange(1, 13).reshape(3, 4)`. Use slicing to print its 2nd row,
   its last column, and every element in even-indexed columns ($0, 2, \dots$).

In [60]:
A = np.arange(1, 13).reshape(3, 4)

print(A)
print(A[1, :])
print(A[:, 3])
print(A[:, 1::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
[ 4  8 12]
[[ 2  4]
 [ 6  8]
 [10 12]]
