In [1]:
import numpy as np

# Chapter 01a — NumPy Arrays: the Basics

In Chapter 00 we built lists of numbers with loops and found it clumsy. **NumPy**
fixes this. Its central object is the **array** (`ndarray`): a grid of numbers
that behaves like a vector or a matrix.

The big idea: an array lets you write math on *whole collections of numbers at
once*, in notation that mirrors the page. A vector $\mathbf{v}\in\mathbb{R}^n$
is a 1D array; a matrix $A\in\mathbb{R}^{m\times n}$ is a 2D array.

Run each cell with **Shift + Enter**. You cannot break anything.

___
## 2. Making an array from a list

The simplest way to build an array is `np.array(...)` from a Python list.
Think of this as writing down a vector $\mathbf{v} = (2, 3, 5, 7)$.

In [5]:
v = np.array([2, 3, 5, 7])   # a 1D array = a vector
print(v)
print(type(v))               # <class 'numpy.ndarray'>

[2 3 5 7]
<class 'numpy.ndarray'>


A list of lists becomes a 2D array — a **matrix**. Each inner list is a row.

$$A = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{pmatrix}$$

In [6]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])    # two rows, three columns
print(A)

[[1 2 3]
 [4 5 6]]
