In [2]:
import numpy as np
import matplotlib.pyplot as plt

rng = np.random.default_rng(0)

## Chapter 02b — Surfaces, Contours & Vector Fields

Many objects in machine learning are functions of **two** variables, like a
loss surface $L(w_1, w_2)$. This notebook shows the standard ways to picture a
function $f(x, y)$ and a vector field, all built on one key idea: the **grid**.

___
### 1. The grid: `np.meshgrid`

To evaluate $f(x, y)$ over a rectangle we need every combination of an $x$ and
a $y$. `np.meshgrid` takes a 1D list of $x$ values and a 1D list of $y$ values
and returns two 2D arrays `X` and `Y` such that `(X[i,j], Y[i,j])` is one grid
point. Then a vectorised formula gives `Z = f(X, Y)` for the whole grid at once.

In [6]:
# A small grid so we can SEE the arrays.
xs = np.linspace(0, 2, 3)   # [0, 1, 2]
ys = np.linspace(0, 1, 2)   # [0, 1]
X, Y = np.meshgrid(xs, ys)

print("X =\n", X)   # x-coordinate at each grid point
print("Y =\n", Y)   # y-coordinate at each grid point
print("X + Y =\n", X + Y) 

X =
 [[0. 1. 2.]
 [0. 1. 2.]]
Y =
 [[0. 0. 0.]
 [1. 1. 1.]]
X + Y =
 [[0. 1. 2.]
 [1. 2. 3.]]


___
So the grid contains:

`(0,0), (1,0), (2,0), (0,1), (1,1), (2,1)`

**Purpose:** create all `(x, y)` points needed to evaluate `f(x, y)` across a region.

____
### 2. A function of two variables

Let
$$f(x, y) = \exp\!\big(-(x^2 + y^2)\big),$$
a smooth "bump" centered at the origin. We build a fine grid and evaluate it.

In [7]:
xs = np.linspace(-2, 2, 200)
ys = np.linspace(-2, 2, 200)
X, Y = np.meshgrid(xs, ys)

Z = np.exp(-(X ** 2 + Y ** 2))
print("Z has shape", Z.shape)

Z has shape (200, 200)
