In [1]:
import numpy as np

## Chapter 04a — Matrices & Linear Transformations

A **matrix** is a rectangular grid of numbers. On paper we write

$$A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}.$$

In NumPy a matrix is simply a **2-D array**. In this notebook we learn how to
build matrices, do arithmetic with them, multiply them with `@`, and — most
importantly — *see* what a matrix **does**: a matrix is a machine that
**transforms space** (it rotates, scales, and shears points).

Run each cell with **Shift + Enter**. Change numbers and re-run to build
intuition.

_____
### 1. A matrix is a 2-D array

We give `np.array` a list of rows. The **shape** is `(rows, columns)`.

In [6]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])    # 2 rows, 3 columns

print(A)
print("shape:", A.shape)     # (2, 3)  ->  2 rows, 3 columns
print("rows :", A.shape[0])  # 2
print("cols :", A.shape[1])  # 3

[[1 2 3]
 [4 5 6]]
shape: (2, 3)
rows : 2
cols : 3


In [7]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A[0, 0])   # top-left entry      -> 1
print(A[1, 2])   # row 1, col 2        -> 6
print(A[0, :])   # the whole first row -> [1 2 3]
print(A[:, 1])   # the whole 2nd column-> [2 5]

1
6
[1 2 3]
[2 5]


____
### 2. The transpose $A^\top$

The **transpose** flips a matrix across its diagonal: rows become columns. If
$A$ is $2\times 3$ then $A^\top$ is $3\times 2$, and $(A^\top)_{ij}=A_{ji}$.

In [10]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A)
print(A.T)
print(A.T.shape)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
(3, 2)
